# Basic
title: Taomi
subtitle: web coder
welcome_message: <a href="https://github.com/BKHole" target="_blank">Welcome to my house</a>
creator: <a href="https://github.com/BKHole">@Taomi</a>
repository: BKHole/bkhole.github.io
url: "https://bkhole.github.io/"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
  title: Blog
  description: Visit blog

# Navigation buttons in the front page.
nav:
  - {
      title: Projects,
      description: My Projects,
      url: "https://github.com/BKHole",
    }
  # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
  disqus: vno-jekyll
  # duoshuo:

# Social
social:
  weibo: 5183157681
  github: BKHole
  twitter:
  gplus:
  mail: 1332051236@qq.com

# Google Analytics
ga:
  # id: your_ga_id
  # host: your_host
# 对 css 和 js 资源的 cdn 加速配置
cdn:
  jsdelivr:
    enabled: true
