# Basic
title: BKHole
subtitle: A blog-orientation theme for Jekyll
welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: Welcome to my house.


permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'https://github.com/BKHole'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: <a href="http://weibo.com/u/5183157681" target="_blank"></a>
    github: <a href="https://github.com/BKHole" target="_blank"></a>
    twitter: 
    gplus: 107108267983477358170
    mail: 1332051236@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
